[build]
  # Comando para construir Quartz
  command = "git submodule update --remote content && npx quartz build"
  # Carpeta que Netlify publicará
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  # Asegura que Netlify clone los submódulos
  GIT_SUBMODULE_STRATEGY = "recursive"
